spring:
  profiles:
    active: prod

---
spring:
  profiles: prod

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect
    open-in-view: false

  h2:
    console:
      enabled: true
      path: /h2

server:
  port: 8081

my:
  env:
    code: Prod profile
url:
  microservice:
    algo: http://algo:8082/inn

---

spring:
  profiles: dev

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect
    open-in-view: false

  h2:
    console:
      enabled: true
      path: /h2

server:
  port: 8088

url:
  microservice:
    algo: http://localhost:8082/inn


